version: "3.9"

services:
  db:
    image: postgres:13.2-alpine
    container_name: ${PROJECT}-db
    restart: always
    networks:
      - ${PROJECT}-network
    volumes:
      - ${PROJECT}-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  app:
    image: ${PROJECT}-app
    build:
      context: .
      dockerfile: ./Dockerfile.app
    container_name: ${PROJECT}-app
    restart: always
    networks:
      - ${PROJECT}-network
    volumes:
      - ./../:/code
    ports:
      - ${APP_PORT}:80
    env_file:
      - ./.env
    working_dir: /code
    command: tail -f /dev/null

volumes:
  dotnet-bots-pgdata:
    name: ${PROJECT}-pgdata

networks:
  dotnet-bots-network:
    name: ${PROJECT}-network
